version: '3.8'

# Notice the target is set to development
# Bind mount for working directory to allow hot reloading
# Anonymouse volume for node_modules to prevent overwriting with COPY in Dockerfile

services:
  give-it-a-name:
    build:
      context: .
      target: development
    image: my-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # env_file:
    #   - ./nodejs/.env
