name: Get GCP secret

run-name: Using workload federated identity with GH

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main # Adjust as per your preference

jobs:
  get-secret:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions (allegedly mandatory).
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/github'
          workload_identity_provider: 'projects/1046457465833/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'github-actions@tranquil-app-397220.iam.gserviceaccount.com'

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Now you can run gcloud commands authenticated as the impersonated service account.
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud secrets versions access "latest" --secret "test-secet"
          # gcloud config list project
